[package]
name = "pokemon"
version = "0.1.0"
edition = "2021"
authors = ["Dr460n4ir3 LLC <mcneilly@error-404.dev>"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.6.0", features = ["dynamic"]}
bevy-inspector-egui = "0.8"
rand = "0.8.5"
