[package]
name = "pokemon"
version = "0.1.0"
edition = "2021"
author = "Dr460n4ir3 LLC"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.6", features = ["dynamic"]}